views.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for, flash
from .models import *
from werkzeug.utils import secure_filename
import os
from flask_login import login_required, current_user
from ._init_ import db

views = Blueprint('views', __name__)  # views can be changed
UPLOAD_IMG = "website/static/upload_image/"  # Path to the uploaded images
UPLOAD_FILES = "website/static/upload_file/"  # Path to the uploaded files


@views.route('/', defaults={'game_title': None})
@views.route('/<game_title>')
def home(game_title):
    # If the user is logged in, redirect to dashboard
    #if current_user.is_authenticated:
    #return redirect(url_for('views.dashboard'))

    if game_title:
        return redirect(url_for('views.gameinfo', game_title=game_title))

    # Fetch recently added games (assuming you're sorting by game ID)
    recently_added_games = Game.query.order_by(Game.id.desc()).limit(6).all()

    # Categorize games by genres
    all_games = Game.query.all()
    games_by_genre = {}
    for game in all_games:
        for genre in game.categories:
            if genre not in games_by_genre:
                games_by_genre[genre] = []
            games_by_genre[genre].append(game)

    return render_template("home.html",
                           recently_added_games=recently_added_games,
                           games_by_genre=games_by_genre,
                           user=current_user)


@views.route(
    '/gameinfo/<game_title>'
)  # this is a game info page that would show, donation etc. Will be Dynamically changing
def gameinfo(game_title):
    # Query the game based on the provided title
    game = Game.query.filter_by(title=game_title).first()

    # If the game is not found, handle the error
    if game is None:
        return render_template('error.html', message="Game not found")

    # Render the gameinfo.html template with the game information
    return render_template('gameinfo.html', game=game)


@views.route(
    '/dashboard', defaults={'game_title': None}
)  #Similar to Home but replace login and register with redirect to orders and logout
@views.route('/dashboard/<game_title>')
@login_required  # user needs to be login, otherwise redirect to login page
def dashboard(game_title):
    if game_title:
        return redirect(url_for('views.gameinfo', game_title=game_title))

    # Fetch recently added games (assuming you're sorting by game ID)
    recently_added_games = Game.query.order_by(Game.id.desc()).limit(6).all()

    # Categorize games by genres
    all_games = Game.query.all()
    games_by_genre = {}
    for game in all_games:
        for genre in game.categories:
            if genre not in games_by_genre:
                games_by_genre[genre] = []
                games_by_genre[genre].append(game)

    return render_template("home.html",
                           recently_added_games=recently_added_games,
                           games_by_genre=games_by_genre,
                           user=current_user)


@views.route(
    '/browse'
)  #List every single game, Do not include download here change to add to cart
def browse():
    # Query all games from the database
    games = Game.query.all()
    # Filter out games with None image paths
    games_with_images = [game for game in games if game.image is not None]
    return render_template("browse.html", games=games_with_images)


@login_required  # user needs to be login, otherwise redirect to login page
@views.route('/transaction')  #check each order
def transaction():
    return render_template("transaction.html")


@login_required  # user needs to be login, otherwise redirect to login page
@views.route(
    '/library')  #To download games from, listed similar to how it is in browse
def library():
    return render_template("library.html")


@login_required  # user needs to be login, otherwise redirect to login page
@views.route('/checkout', methods=[
    'GET', 'POST'
])  #fill out user details, payment details, etc and purchase games
def checkout():
    if request.method == 'POST':
        # Extract data from the form
        name = request.form.get('firstName')
        address = request.form.get('address')
        credit_card = request.form.get('creditCard')

        # Update the current user's customer information
        current_user.customer.name = name
        current_user.customer.address = address
        current_user.customer.credit_card = credit_card

        # Check if the current user has a cart
        if current_user.cart is None:
            flash('No games in cart', 'error')

        # Get the games from the user's cart
        games_in_cart = current_user.cart.games

        # Add each game in the cart to user.games
        for game in games_in_cart:
            current_user.games.append(game)

        # Get the games from the user's cart
        games_in_cart = current_user.cart.games

        # Create a new Order instance
        order = Orders(cart_id=current_user.cart.id,
                       user_id=current_user.id,
                       date_purchased=datetime.now(),
                       subtotal=current_user.cart.subtotal,
                       status=True)
        # add games from cart to order
        for game in current_user.cart.games:
            order.games.append(game)
        # Add the new Order instance to the session
        db.session.add(order)
        db.session.commit()
        # Clear the cart
        current_user.cart.games = []
        db.session.commit()

        return redirect(url_for('views.thank_you'))
    return render_template("checkout.html")


@views.route('/uploadgame', methods=['GET', 'POST'])
@login_required  # user needs to be login, otherwise redirect to login page
def uploadgame():
    if request.method == 'POST':
        # Extract data from the form
        title = request.form.get('game_title')
        developer_name = request.form.get('game_developer')
        genres = request.form.getlist('genre[]')
        price = float(request.form.get('game-price'))
        description = request.form.get('game_description')
        donation = request.form.get('game_donation')
        # Handle file uploads for game image and zip file
        game_image = request.files['game_image']
        game_zip = request.files['zip_file']

        # Store the file
        game_image_filename = secure_filename(game_image.filename)
        game_image_path = os.path.join(UPLOAD_IMG, game_image_filename)
        os.makedirs(os.path.dirname(game_image_path), exist_ok=True)
        game_image.save(game_image_path)

        game_zip_filename = secure_filename(game_zip.filename)
        game_zip_path = os.path.join(UPLOAD_FILES, game_zip_filename)
        os.makedirs(os.path.dirname(game_zip_path), exist_ok=True)
        game_zip.save(game_zip_path)

        # Query the Developer object based on the provided developer name
        developer = Developer.query.filter_by(devName=developer_name).first()
        if not developer:
            # Check if a Developer with the same email already exists
            existing_developer = Developer.query.filter_by(
                email=current_user.email).first()
            if existing_developer:
                # If a Developer with the same email already exists, use that Developer
                developer = existing_developer
            else:
                # If no Developer with the same email exists, create a new Developer
                developer = Developer(devName=developer_name,
                                      donation=donation,
                                      email=current_user.email,
                                      user_id=current_user.id)
                db.session.add(developer)
                db.session.commit()

        # Create a new Game object and save it to the database, appending genre
        new_game = Game(title=title,
                        developer_id=developer.id,
                        price=price,
                        description=description,
                        image=game_image_path,
                        data=game_zip_path)
        db.session.add(new_game)
        db.session.commit()
        for value in genres:
            category = Game_catalog.query.filter_by(category=value).first()
            if category:
                new_game.categories.append(
                    category
                )  # updates game_catalog_games table to link game to category
        db.session.commit()

        return redirect(
            url_for('views.home'))  # Redirect to the home page after upload

    return render_template("uploadgame.html")


@views.route('/cart', methods=['GET', 'POST'])  #checking the cart itself
@login_required  # user needs to be login, otherwise redirect to login page
def cart():
    # Check if the current user has a cart
    if current_user.cart is None:
        return render_template("cart.html", games=[])

    subtotal = current_user.cart.subtotal

    # Get the games in the current user's cart
    if request.method == 'POST':  # removes game from cart if method is POST
        game_id = request.form.get('game_id')
        game = Game.query.get(game_id)
        if game in current_user.cart.games:
            current_user.cart.games.remove(game)
            db.session.commit()
            games_in_cart = current_user.cart.games
            return render_template("cart.html", games=games_in_cart)

    games_in_cart = current_user.cart.games
    return render_template("cart.html", games=games_in_cart, subtotal=subtotal)


@views.route('/add_to_cart', methods=[
    'POST'
])  # add games to cart, for a seemless experience, using javascript to POST
@login_required  # user needs to be login, otherwise redirect to login page
def add_to_cart(
):  # this would provide functionality of adding games to cart, thinking of doing this without reloading the page
    game_id = request.form.get('game_id')

    # Check if the current user has a cart

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="../static/img/logo-game-controller-b-1.png" type="image/x-icon">
    <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
  <link rel="stylesheet" href="../static/css/styles.css">
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" id="browse" href="/">Home</a>
          <a class="nav-item nav-link" id="browse" href="/browse">Browse</a>
          <a class="nav-item nav-link" id="uploadgame" href="/uploadgame">Upload Game</a>
        </div>
        
      
        <div class="navbar-nav">
          {% if current_user.is_authenticated %}
            <a class="nav-item nav-link" href="/transaction">Orders</a>
            <a class="nav-item nav-link" href="/library">Library</a>
            <a class="nav-item nav-link" href="/logout">Logout</a>
          {% else %}
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
          <a class="nav-item nav-link" href="/cart">
            <img src="../static/img/basket-cart-icon-27.png" alt="Cart" class="cart-icon">
          </a>
        </div>
      </div>
    </nav>         
    <div class="container custom-container">
      {% block content %}
      {% endblock %}
    </div>


    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/cart.html
{% extends "base.html" %}
{% block title %}Cart{% endblock %}
{% block content %}
<div class="container">
    <h1 class="white-text">Your Shopping Cart</h1>
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th class="white-text">Title</th>
                        <th class="white-text">Description</th>
                        <th class="white-text">Price</th>
                        <th class="white-text">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for game in games %}
                    <tr>
                        <td class="white-text">{{ game.title }}</td>
                        <td class="white-text">{{ game.description }}</td>
                        <td class="white-text">${{ game.price }}</td>
                        <td>
                            <form action="{{ url_for('views.cart') }}" method="POST">
                                <input type="hidden" name="game_id" value="{{ game.id }}">
                                <button type="submit" class="btn btn-danger">Remove</button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="subtotal">
                <strong>Subtotal:</strong> ${{ subtotal }}
            </div>
            <a href="{{ url_for('views.checkout') }}" class="btn btn-primary">Checkout</a>
        </div>
    </div>
</div>
{% endblock %}

templates/checkout.html
{% extends "base.html" %}
{% block title %}Checkout{% endblock %}
{% block content %}
<div class="container">
    <h1>Checkout</h1>
    <form method="post">
        <div class="mb-3">
            <label for="firstName" class="form-label">First Name</label>
            <input type="text" class="form-control" id="firstName" name="firstName" required>
        </div>
        <div class="mb-3">
            <label for="lastName" class="form-label">Last Name</label>
            <input type="text" class="form-control" id="lastName" name="lastName" required>
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email Address</label>
            <input type="email" class="form-control" id="email" name="email" required>
        </div>
        <div class="mb-3">
            <label for="address" class="form-label">Address</label>
            <input type="text" class="form-control" id="address" name="address" required>
        </div>
        <div class="mb-3">
            <label for="city" class="form-label">City</label>
            <input type="text" class="form-control" id="city" name="city" required>
        </div>
        <div class="mb-3">
            <label for="state" class="form-label">State</label>
            <input type="text" class="form-control" id="state" name="state" required>
        </div>
        <div class="mb-3">
            <label for="zip" class="form-label">Zip Code</label>
            <input type="text" class="form-control" id="zip" name="zip" required>
        </div>
        <div class="mb-3">
            <label for="country" class="form-label">Country</label>
            <input type="text" class="form-control" id="country" name="country" required>
        </div>
        <div class="mb-3">
            <label for="creditCard" class="form-label">Credit Card Number</label>
            <input type="text" class="form-control" id="creditCard" name="creditCard" required>
        </div>
        <div class="mb-3">
            <label for="expDate" class="form-label">Expiration Date</label>
            <input type="text" class="form-control" id="expDate" name="expDate" required>
        </div>
        <div class="mb-3">
            <label for="cvv" class="form-label">CVV</label>
            <input type="text" class="form-control" id="cvv" name="cvv" required>
        </div>
        <!-- Add more fields as needed -->
        <button type="submit" class="btn btn-primary">Place Order</button>
    </form>
</div>
{% endblock %}

templates/dashboard.html
<!-- This file should be like home.html but for once you logged in. 
You could change the menu bar on the top where it has login to say the username instead and the option of log out instead of sign up. -->

{% extends "base.html" %} {% block title %}Dashboard{% endblock %}

templates/demos.html
{% extends "base.html" %} {% block title %}Demos{% endblock %}

templates/gameinfo.html
{% extends "base.html" %}
{% block title %}Game Information - {{ game.title }}{% endblock %}
{% block content %}
<div class="container">
    <h1>{{ game.title }}</h1>
    <div class="row">
        <div class="col-md-6">
            <img src="../{{ game.image.split('website/')[-1] }}" class="card-img-top" alt="{{ game.image.split('website/')[-1] }}">
        </div>
        <div class="col-md-6">
            <p><strong>Description:</strong> {{ game.description }}</p>
            <p><strong>Price:</strong> ${{ game.price }}</p>
            <p><strong>Developer:</strong> {{ game.developer.devName }}</p>
            <p><strong>Genres:</strong>
                {% for category in game.categories %}
                    {{ category.category }}{% if not loop.last %}, {% endif %}
                {% endfor %}
            </p>
            {% if game.developer.donation %}
            {% set donation_link = game.developer.donation %}
            {% if 'http://' in donation_link or 'https://' in donation_link %}
                {% set donation_url = donation_link %}
            {% else %}
                {% set donation_url = '//' + donation_link %}
            {% endif %}
            <p><strong>Donation Link:</strong> <a href="{{ donation_url }}" class="btn btn-info" target="_blank">Donate Now</a></p>
        {% endif %}
        
            <!-- Button group to add the game to the cart and buy now -->
            <div class="btn-group" role="group" aria-label="Add to Cart or Buy Now">
                <!-- Add to Cart button -->
                <form id="add-to-cart-form" action="{{ url_for('views.add_to_cart') }}" method="POST">
                    <input type="hidden" name="game_id" value="{{ game.id }}">
                    <button type="button" id="add-to-cart-btn" class="btn btn-success">Add to Cart</button>
                </form>
                <!-- Buy Now button -->
                <form action="{{ url_for('views.add_to_cart_and_redirect') }}" method="POST">
                    <input type="hidden" name="game_id" value="{{ game.id }}">
                    <button type="submit" class="btn btn-primary">Buy Now</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('add-to-cart-btn').addEventListener('click', function() {
        var form = document.getElementById('add-to-cart-form');
        var formData = new FormData(form);

        fetch(form.action, {
            method: form.method,
            body: formData
        })
        .then(response => response.json())
        .then(data => {
            if (data.status === 'success') {
                alert(data.message);  // Show success message as alert
            } else {
                alert(data.message);  // Show failure message as alert
            }
        })
        .catch(error => {
            console.error('Error:', error);
        });
    });
</script>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
    <h1>Recently Added</h1>
    <div class="row">
        {% for game in recently_added_games %}
        <div class="col-md-4 mb-4">
            <div class="card custom-card">
                <img src="../{{ game.image.split('website/')[-1] }}" class="card-img-top" alt="{{ game.title }}">
                <div class="card-body">
                    <h5 class="card-title">{{ game.title }}</h5>
                    <p class="card-text">{{ game.description }}</p>
                    <p class="card-text">Price: ${{ game.price }}</p>
                    <a href="{{ url_for('views.gameinfo', game_title=game.title) }}" class="btn btn-primary">View Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Add sections for games by genre -->
    {% for genre, games in games_by_genre.items() %}
    <h1>{{ genre.category }}</h1>
    <div class="row">
        {% for game in games %}
            <div class="col-md-4 mb-4">
                <div class="card custom-card">
                    <img src="../{{ game.image.split('website/')[-1] }}" class="card-img-top" alt="{{ game.title }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ game.title }}</h5>
                        <p class="card-text">{{ game.description }}</p>
                        <p class="card-text">Price: ${{ game.price }}</p>
                        <a href="{{ url_for('views.gameinfo', game_title=game.title) }}" class="btn btn-primary">View Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endfor %}
</div>
{% endblock %}

templates/library.html
{% extends "base.html" %}
{% block title %}Library{% endblock %}

<!-- assumes you have access to the user's purchased games through the current_user --> 
{% block content %}
<div class="container">
    <h1 class="white-text">Your Library</h1>
    <div class="row">
        {% if current_user.is_authenticated %}
            {% if current_user.games %}
                {% for game in current_user.games %}
                    <div class="col-md-4 mb-4">
                        <div class="card custom-card">
                            <img src="../{{ game.image.split('website/')[-1] }}" class="card-img-top" alt="{{ game.title }}">
                            <div class="card-body">
                                <h5 class="card-title white-text">{{ game.title }}</h5>
                                <p class="card-text white-text">{{ game.description }}</p>
                                <p class="card-text white-text">Price: ${{ game.price }}</p>
                                <div class="button-container">
                                    <a href="{{ url_for('views.gameinfo', game_title=game.title) }}" class="btn btn-primary mr-2">View Details</a>
                                    <a href="../{{ game.data.split('website/')[-1] }}" class="btn btn-success white-text" download>Download</a>
                                </div>    
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p class="white-text">Your library is empty. Start exploring and adding games!</p>
            {% endif %}
        {% else %}
            <p class="white-text">Please log in to view your library.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    {% endblock %}

templates/popup_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Popup Message</title>
    <script>
        window.onload = function() {
            alert("{{ message }}");
        };
    </script>
</head>
<body>
</body>
</html>

templates/sign_up.html
{% extends "base.html" %} 
{% block title %}Sign Up{% endblock %} 
{% block content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
      required
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
      required
    />
  </div>
  <div class="form-group">
    <label for="dob">Date of Birth</label>
    <input
      type="date"
      class="form-control"
      id="dob"
      name="dob"
      required
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
      required
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
      required
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

templates/thankyou.html
{% extends "base.html" %}
{% block title %}Thank You{% endblock %}
{% block content %}
<div class="container center-content">
    <div class="text-center">
        <h1>Thank You for Your Purchase!</h1>
        <p>Your order has been placed successfully.</p>
        <!-- Add more content here if needed -->
    </div>
</div>
{% endblock %}

templates/transaction.html
{% extends "base.html" %}
{% block title %}Transaction History{% endblock %}

<!-- assumes you have access to the user's purchased games through the current_user --> 
{% block content %}
<div class="container">
    <h1>Transaction History</h1>
    <div class="row">
        {% if current_user.is_authenticated %}
            {% if current_user.orders %}
                <table class="table">
                    <thead>
                        <tr>
                            <th class="white-text">Date Purchased</th>
                            <th class="white-text">Game Title</th>
                            <th class="white-text">Price</th>
                            <th class="white-text">Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for order in current_user.orders %}
                            {% for game in order.games %}
                                <tr>
                                    <td class="white-text">{{ order.date_purchased }}</td>
                                    <td class="white-text">{{ game.title }}</td>
                                    <td class="white-text">${{ game.price }}</td>
                                    <td class="white-text">{% if order.status %}Purchased{% else %}Not Purchased{% endif %}</td>
                                </tr>
                            {% endfor %}
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No transaction history found.</p>
            {% endif %}
        {% else %}
            <p>Please log in to view your transaction history.</p>
        {% endif %}
    </div>
</div>
{% endblock %}